disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - identifier_name
opt_in_rules:
  - force_unwrapping
excluded:
  - Pods
identifier_name:
  min_length: 2
