name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -workspace 'WBooks.xcworkspace' -scheme 'WBooks' CODE_SIGN_IDENTITY="Apple Development" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - name: Run tests
      run: xcodebuild test -workspace 'WBooks.xcworkspace' -scheme 'WBooks' -destination 'platform=iOS Simulator,name=iPhone 8'
